### ISSUE TITLE
visualization about the real-time mesh reconstruction

### ISSUE THREAD

**Issue by xupeng9910** [oppo-us-research/NARUTO#2]
Hello author, thanks for your excellent work! I follow the Running NARUTO and use "bash scripts/naruto/run_replica.sh office0 1 NARUTO 1" command. But it only show the real-time RGB-D image, i want to know if it can show the mesh real time when running this algrithom. Thank you!

**Comment by Huangying-Zhan** [comment]
Hi @xupeng9910 , thanks for your interest in our work. Our current released version only supports visualizing the RGB-D image in real-time. To visualize the intermediate mesh / other data (such as path planning), you have to save those intermediate data while running and run the visualization script at the end.
Please refer to the configuration here to turn on this function.
 https://github.com/oppo-us-research/NARUTO/blob/04988b4943d252072eaf191379fbaef438c206f6/configs/default.py#L143 

To run the visualization, you can use the script here:
https://github.com/oppo-us-research/NARUTO/blob/release/scripts/evaluation/visualize_naruto.sh

**Comment by xupeng9910** [comment]
I get it! Thanks for your reply!
