### ISSUE TITLE
Conda Installation Script error

### ISSUE THREAD

**Issue by rohitmenon86** [oppo-us-research/NARUTO#3]
Line 7 of build.sh has source activate naruto instead of conda activate naruto https://github.com/oppo-us-research/NARUTO/blob/d29869eba75d8e67446706e1ae22b4720956e006/scripts/installation/conda_env/build.sh#L7

**Comment by Huangying-Zhan** [comment]
@rohitmenon86 Thank you for bringing this to our attention. We have updated the script to include `conda activate`, which is compatible with newer versions of Conda.
