### ISSUE TITLE
checkpoint files

### ISSUE THREAD

**Issue by 3D-A** [oppo-us-research/NARUTO#4]
Thank you for your work

**Comment by Huangying-Zhan** [comment]
@WangShuaixian are you looking for the final checkpoint files or the final mesh files?

**Comment by WangShuaixian** [comment]
Thank you for your reply and support ！  If possible, I want both. Thank you very much！

**Comment by WangShuaixian** [comment]
> @WangShuaixian are you looking for the final checkpoint files or the final mesh files?

Thank you for your reply and support！ If possible, I want both. Thank you very much！

**Comment by WangShuaixian** [comment]
Thanks for the great work，I have slove it
